collections:
  authors:
    output: true
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
